### ISSUE TITLE
PCS Cluster Setup - Clarification if 'enable --all' is set 

### ISSUE THREAD

**Issue by tlb1galaxy** [OndrejHome/ansible.pcs-modules-2#38]
PCS-Modules-2 version:

23.0.0

Question:

When configuring and setting up a new cluster, I would normally run the following commands/logic:

```
pcs cluster auth nfs_node01 nfs_node02
pcs cluster setup --start --name nfsclst01 nfs_node01 nfs_node02
pcs cluster enable --all
```

When running the Ansible 'pcs_clsuter' task, does the module automatically facilitate the 'start' & 'enable' command equivalent?  I could not determine either way definitively.
```
- name: pcs_cluster_initial_setup
  pcs_cluster:
    node_list: "{% for item in play_hosts %}{{ hostvars[item]['ansible_fqdn'] }} {% endfor %}"
    cluster_name: "{{ var_pcs_cluster_name }}"
    state: 'present'
  run_once: True
```

Or would I have to call those commands from a shell task within Ansible?
Thanks
