### ISSUE TITLE
pcs_constraint_location: allow specification of resource-discovery option

### ISSUE THREAD

**Issue by chenwangkai** [OndrejHome/ansible.pcs-modules-2#48]
Hello @OndrejHome 

my pcs command as follow:

`pcs constraint location skyform_group-clone avoids node1 resource-discovery=never`

here is my ansible task code:
```
- name: resource skyform_group-clone avoids running on node1
  pcs_constraint_location:
    resource: 'skyform_group-clone'
    node_name: "node1"
    score: '-INFINITY'
```

my question: how to specify resource-discovery option with ansible.pcs-modules-2, such as resource-discovery=never
